# Makefile
# Center servos Arduino sketch
ARDUINO_DIR = /Applications/Arduino.app/Contents/Resources/Java
BOARD_TAG = atmega328
ARDUINO_PORT = /dev/tty.usbserial-*
ARDUINO_LIBS = Servo

include ../Arduino.mk
